# → Einfacher Name der Pipeline.
# → Wird im GitHub Actions UI angezeigt.
name: CI Pipeline

# push auf main → baut & veröffentlicht neue Versionen
# pull_request → prüft Änderungen, bevor sie gemerged werden (darf nicht in main gemerged werden, wenn Build fehlschlägt)
on:
  push:
    branches:
      - main
    pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    # GitHub Actions startet eine virtuelle Maschine auf Ubuntu.
    # Das ist dein Build‑Agent (CI Runner)
    # Hat Docker & Node bereits vorinstalliert → schneller
    runs-on: ubuntu-latest

    steps:
      # Dein Repository wird in die VM geklont
      # Ohne diesen Schritt → GitHub Actions hat keinen Code, den sie bauen könnte
      - name: Check out code
        uses: actions/checkout@v4

      # CI‑Builds müssen dieselbe Node-Version nutzen wie lokal & Prod
      #verhindert: „bei mir läuft's, in CI nicht“
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # npm installiert alle Dependencies
      # benötigt, damit Vite den Build machen kann
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # Tests werden ausgeführt
      # Stellt sicher, dass dein Code funktioniert
      # Verhindert, dass fehlerhafter Code in Produktion gelangt
      # Ohne --run würde Vitest im Watch-Modus starten und der Job nie fertig werden.
      - name: Run tests
        working-directory: frontend
        run: npm test -- --run

      # Vite erzeugt dist/
      # CI bricht sofort ab, wenn dein Code nicht baut
      # Qualitätssicherung: Broken Builds kommen nicht in Docker oder in die Cloud
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Continuous Deployment (CD)
      # Image wird in Azure Web App deployed
      # Nach jedem Push auf main ist die neueste Version live

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Loin zu Azure Container Registry
      - name: Login to ACR
        run: az acr login --name project1registry

      # CI baut dein Production Image mit nginx
      #Du bekommst zwei Tags:
      #1️⃣ latest
      #→ steht für „aktuellste Version“

      #2️⃣ {github.sha}
      # eindeutige Versionierung pro Commit
      # perfekt für Rollbacks
      # wird in echten DevOps‑Pipelines immer verwendet
      - name: Build docker image
        run: |
          docker build \
            -t project1registry.azurecr.io/project-1-frontend:latest \
            -t project1registry.azurecr.io/project-1-frontend:${{ github.sha }} \
            ./frontend

      # Danach ist dein Image in Docker Hub verfügbar
      # Jede Cloud (Azure, Render, AWS) kann dieses Image deployen
      # Du hast Versionierung und Rückverfolgbarkeit
      # Du kannst Deployment automatisieren (CD)
      - name: Push Docker image
        run: |
          docker push project1registry.azurecr.io/project-1-frontend:latest
          docker push project1registry.azurecr.io/project-1-frontend:${{ github.sha }}

      # Deplyoment auf Staging
      - name: Restart Azure Web App to deploy new image
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart \
              --name project1-frontend-app \
              --resource-group project1-rg \
              --slot staging

      - name: Swap Staging to Production
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deployment slot swap \
              --name project1-frontend-app \
              --resource-group project1-rg \
              --slot staging \
              --target-slot production
